[package]
name = "hybrid-vector-search"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.18.0"
ordered-float = "4.3.0"
rayon = "1.10.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
